"""Add ML models: detection, ml_job, ml_model

Revision ID: 763ce8c726fc
Revises: 
Create Date: 2025-12-26 17:54:47.362132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763ce8c726fc'
down_revision: Union[str, None] = '000_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('class_names', sa.JSON(), nullable=False),
    sa.Column('input_size', sa.JSON(), nullable=False),
    sa.Column('default_confidence_threshold', sa.Float(), nullable=False),
    sa.Column('default_nms_threshold', sa.Float(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('bbox_x', sa.Float(), nullable=False),
    sa.Column('bbox_y', sa.Float(), nullable=False),
    sa.Column('bbox_width', sa.Float(), nullable=False),
    sa.Column('bbox_height', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_detections_camera_id', 'detections', ['camera_id'], unique=False)
    op.create_index('ix_detections_class_name', 'detections', ['class_name'], unique=False)
    op.create_index('ix_detections_confidence', 'detections', ['confidence'], unique=False)
    op.create_index('ix_detections_created_at', 'detections', ['created_at'], unique=False)
    op.create_index('ix_detections_recording_id', 'detections', ['recording_id'], unique=False)
    op.create_table('ml_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('frames_processed', sa.Integer(), nullable=False),
    sa.Column('total_frames', sa.Integer(), nullable=False),
    sa.Column('detections_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ml_jobs_created_at', 'ml_jobs', ['created_at'], unique=False)
    op.create_index('ix_ml_jobs_recording_id', 'ml_jobs', ['recording_id'], unique=False)
    op.create_index('ix_ml_jobs_status', 'ml_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ml_jobs_status', table_name='ml_jobs')
    op.drop_index('ix_ml_jobs_recording_id', table_name='ml_jobs')
    op.drop_index('ix_ml_jobs_created_at', table_name='ml_jobs')
    op.drop_table('ml_jobs')
    op.drop_index('ix_detections_recording_id', table_name='detections')
    op.drop_index('ix_detections_created_at', table_name='detections')
    op.drop_index('ix_detections_confidence', table_name='detections')
    op.drop_index('ix_detections_class_name', table_name='detections')
    op.drop_index('ix_detections_camera_id', table_name='detections')
    op.drop_table('detections')
    op.drop_table('ml_models')
    # ### end Alembic commands ###
