"""Add worker tracking columns to ml_jobs

Revision ID: bfc3f1b7eb27
Revises: 763ce8c726fc
Create Date: 2025-12-27 19:20:32.752646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc3f1b7eb27'
down_revision: Union[str, None] = '763ce8c726fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_jobs', sa.Column('worker_id', sa.String(length=64), nullable=True))
    op.add_column('ml_jobs', sa.Column('last_heartbeat', sa.DateTime(), nullable=True))
    op.create_index('ix_ml_jobs_pending_queue', 'ml_jobs', ['status', 'priority', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ml_jobs_pending_queue', table_name='ml_jobs')
    op.drop_column('ml_jobs', 'last_heartbeat')
    op.drop_column('ml_jobs', 'worker_id')
    # ### end Alembic commands ###
